# Generated by Django 5.0.3 on 2024-06-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
    ]
