# Generated by Django 5.0.6 on 2024-07-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
    ]
