# Generated by Django 5.0.6 on 2024-07-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
