# Generated by Django 5.0.6 on 2024-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0002_remove_producto_editorial_remove_producto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Acceso a CRUD',
                'verbose_name_plural': 'Accesos a CRUD',
            },
        ),
    ]
